#!/bin/bash
#SBATCH -p edu-thesis
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8192M
#SBATCH -N 1
#SBATCH -t 0-5:00

module load cuda/11.8
source /home/diego.calanzone/.bashrc
source activate semantic_models 
cd /home/diego.calanzone/glp/hypernet_learning 

python ../comparative_learning/main.py -i SOLA -o out